const why = `
It is said that loving someone is a choice. That when you love someone you fix problems, grow together, you become a team, you don’t let a misunderstanding ruin everything, you keep fighting to make it through. You also learn to communicate, you try to become a better person for your partner and you are willing to go through thick and thin and you make the choice of loving them, you decide to.

When I met you I realized not all of it was true. I do wanna have a future with you, I want it to be us against the world, I want us to fight through every single problem together but loving you isn’t a choice. When I met you I realized I just do it, it comes from my heart. I don’t decide to love you, I do it naturally. It’s like it comes with me, it’s part of who I am. I was born this way, I was born waiting for you to appear in my life so I could feel it, so that love that has been in me for so long could be given to you.

I love you Leah, I love loving you. You are the person I wanna spend my life with, the one I want to have breakfast with every single morning, the one I make silly surprises for, the one thats waiting for me at home.  I wanna share my life with you, I want you to be part of my big and small moments, I wanna love you for the rest of my life and even in the afterlife. 

You may wonder why you and that’s because to me you are the prettiest girl I have ever seen. I love every single one of your face features. I think you have the prettiest eyes ever, I love the color, the pretty blue is just so perfect, not scary like other people. I also looooove the shape, i love how se hacen chinitos cuando sonríes, me encanta. I love your lashes, I love your nose, I love your lips, the shape is just so perfect for me and they always look so soft and so kissable, I love your cheeks, I love it, they are just so perfect, I just really really love your face. I think you are the most beautiful girl on earth and no one can change my mind. I don’t care what others think or how you see yourself. I know you are the prettiest, absolutely breathtaking, most beautiful and gorgeous girl ever and that is my truth 

I would pick you over anything and anyone. No one is as pretty as you, nor as funny. No one gets me like you do, no one comforts me so quickly, no one can cheer me up so easily and no one knows how to love me like you. You are special, the way you love me is what I need. I would never pick anyone else over you because no one is you. There is one person who owns my heart and that is you. You are the only one who can make me as happy, the only one who makes my days better, the one who makes life make sense, the one who makes me wanna wake up every morning. You give a meaning to my life, everything I do, I always do it for you, for us and that feeling is irreplaceable. No one can make me feel what Leah Korsmo does and no one ever will

You are just the funniest, the nicest, the best that has ever happened to me and I don’t understand how I got so lucky. I would never give you up. I want you, i want my dramatic spoiled girl who can’t take a no for an answer, the girl who tries her best to make me happy and who never fails to make me laugh. I want you and no one else, you are the one I want and the one im keeping for good. I pick you, I choose you today and always.
`;

export default why;
